import type { CharacterEntry } from './characters';

// Dictionary topic filters. A character belongs to a topic when its English definition
// mentions one of the topic's words (plurals match too), or it is listed in `characters`.
type FilterDefinition = { id: string; label: string; words: string[]; phrases?: string[]; characters?: string; unless?: string[] };

const DEFINITIONS: FilterDefinition[] = [
  { id: 'numbers', label: 'Numbers', characters: '零〇一二两三四五六七八九十百千万亿兆半双第数', words: ['zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten', 'hundred', 'thousand', 'million', 'billion', 'number', 'numeral', 'ordinal', 'half', 'double', 'first', 'second', 'third', 'count', 'calculate', 'amount', 'quantity', 'pair', 'dozen', 'percent'] },
  { id: 'measure-words', label: 'Measure words', words: [], phrases: ['measure word', 'classifier', 'unit of'] },
  { id: 'people', label: 'People', words: ['person', 'people', 'man', 'men', 'woman', 'women', 'male', 'female', 'boy', 'girl', 'child', 'children', 'baby', 'infant', 'teacher', 'student', 'friend', 'guest', 'master', 'servant', 'official', 'worker', 'officer', 'neighbour', 'neighbor', 'crowd', 'public', 'citizen', 'hero', 'monk', 'youth', 'elder', 'old man', 'gentleman', 'lady', 'beauty', 'expert', 'scholar'] },
  { id: 'family', label: 'Family', words: ['family', 'father', 'mother', 'parent', 'dad', 'mom', 'mum', 'brother', 'sister', 'son', 'daughter', 'husband', 'wife', 'grandfather', 'grandmother', 'grandpa', 'grandma', 'grandchild', 'uncle', 'aunt', 'nephew', 'niece', 'cousin', 'relative', 'marry', 'marriage', 'wedding', 'ancestor', 'twin', 'in-law', 'son-in-law', 'daughter-in-law', 'widow', 'concubine', 'pregnant', 'filial', 'clan'] },
  { id: 'body', label: 'Body', words: ['body', 'head', 'face', 'eye', 'eyebrow', 'eyelash', 'eyelid', 'ear', 'nose', 'mouth', 'lip', 'tooth', 'teeth', 'tongue', 'throat', 'neck', 'shoulder', 'hand', 'arm', 'elbow', 'wrist', 'finger', 'thumb', 'nail', 'leg', 'knee', 'ankle', 'foot', 'feet', 'toe', 'heart', 'blood', 'skin', 'hair', 'bone', 'stomach', 'belly', 'chest', 'waist', 'back', 'brain', 'muscle', 'liver', 'kidney', 'lung', 'cheek', 'forehead', 'hip', 'buttock', 'navel', 'spine', 'rib', 'bladder', 'gland', 'pupil', 'palm', 'fist', 'breast', 'womb', 'armpit'] },
  { id: 'health', label: 'Health', words: ['ill', 'illness', 'sick', 'sickness', 'disease', 'medicine', 'medical', 'drug', 'doctor', 'hospital', 'pain', 'painful', 'ache', 'health', 'healthy', 'cure', 'heal', 'treat', 'injury', 'injure', 'wound', 'cough', 'fever', 'tumour', 'tumor', 'cancer', 'plague', 'epidemic', 'swollen', 'swell', 'itch', 'sneeze', 'vomit', 'dizzy', 'faint', 'scar', 'sore', 'pus', 'numb', 'paralyzed', 'diarrhea', 'blind', 'deaf', 'mute', 'tired', 'exhausted', 'tinea', 'pox', 'acupuncture', 'moxibustion'] },
  { id: 'feelings', label: 'Feelings', words: ['love', 'like', 'happy', 'happiness', 'glad', 'joy', 'joyful', 'pleased', 'sad', 'sorrow', 'sorrowful', 'grief', 'angry', 'anger', 'rage', 'fear', 'afraid', 'fearful', 'frightened', 'frighten', 'scared', 'worry', 'worried', 'anxious', 'laugh', 'smile', 'cry', 'weep', 'feel', 'feeling', 'emotion', 'surprise', 'surprised', 'shock', 'lonely', 'shame', 'ashamed', 'embarrassed', 'envy', 'jealous', 'hate', 'regret', 'pity', 'sympathy', 'proud', 'pride', 'calm', 'hope', 'wish', 'miss', 'annoyed', 'upset', 'disappointed', 'sigh', 'grateful', 'thank', 'sorry', 'apology', 'guilty', 'bored', 'excited', 'passion', 'desire'] },
  { id: 'food', label: 'Food & drink', words: ['food', 'eat', 'drink', 'rice', 'tea', 'fruit', 'vegetable', 'meat', 'bread', 'noodle', 'dumpling', 'sugar', 'salt', 'salty', 'meal', 'cook', 'wine', 'beer', 'alcohol', 'milk', 'egg', 'soup', 'cake', 'sauce', 'vinegar', 'oil', 'flour', 'taste', 'sweet', 'sour', 'bitter', 'spicy', 'hungry', 'thirsty', 'bake', 'roast', 'fry', 'boil', 'steam', 'stew', 'braise', 'chew', 'bite', 'lick', 'honey', 'bean', 'tofu', 'garlic', 'ginger', 'onion', 'pepper', 'chives', 'mushroom', 'apple', 'pear', 'peach', 'grape', 'orange', 'lemon', 'lychee', 'banana', 'melon', 'jujube', 'chestnut', 'walnut', 'olive', 'coffee', 'juice', 'cheese', 'porridge', 'flavour', 'flavor', 'ravioli', 'wonton', 'breakfast', 'lunch', 'dinner', 'feast', 'kitchen', 'chopsticks', 'bowl', 'plate', 'spoon', 'pot', 'wheat', 'sorghum', 'millet', 'barley', 'buckwheat', 'glutinous'] },
  { id: 'animals', label: 'Animals', words: ['animal', 'beast', 'livestock', 'dog', 'cat', 'horse', 'cow', 'cattle', 'ox', 'calf', 'sheep', 'lamb', 'goat', 'pig', 'chicken', 'hen', 'duck', 'goose', 'bird', 'fowl', 'fish', 'insect', 'bug', 'tiger', 'lion', 'leopard', 'panther', 'dragon', 'snake', 'monkey', 'ape', 'macaque', 'mouse', 'rat', 'rabbit', 'bear', 'wolf', 'fox', 'deer', 'elephant', 'camel', 'donkey', 'mule', 'crane', 'eagle', 'hawk', 'crow', 'sparrow', 'swallow', 'magpie', 'pigeon', 'dove', 'quail', 'owl', 'phoenix', 'turtle', 'tortoise', 'frog', 'toad', 'bee', 'butterfly', 'moth', 'ant', 'fly', 'mosquito', 'worm', 'earthworm', 'spider', 'scorpion', 'locust', 'cicada', 'cockroach', 'firefly', 'bat', 'whale', 'shark', 'crocodile', 'alligator', 'crab', 'shrimp', 'oyster', 'clam', 'snail', 'conch', 'lizard', 'squid', 'cuttlefish', 'carp', 'rhinoceros', 'gorilla', 'gull', 'mandarin duck', 'silkworm', 'nest', 'feather', 'wing', 'tail', 'fur', 'hoof', 'claw', 'paw', 'mane', 'shell', 'hunt', 'herd', 'hatch', 'cub', 'chick'] },
  { id: 'plants', label: 'Plants', words: ['plant', 'tree', 'flower', 'blossom', 'bud', 'grass', 'leaf', 'leaves', 'root', 'branch', 'twig', 'seed', 'sprout', 'seedling', 'bamboo', 'lotus', 'willow', 'pine', 'cypress', 'elm', 'maple', 'banyan', 'orchid', 'chrysanthemum', 'rose', 'jasmine', 'peony', 'moss', 'reed', 'thorn', 'vine', 'crop', 'grain', 'harvest', 'petal', 'stem', 'forest', 'wood', 'woods', 'garden', 'orchard', 'cotton', 'hemp', 'mulberry', 'taro', 'potato', 'radish', 'celery', 'pea', 'fungus', 'wither', 'bloom'] },
  { id: 'nature', label: 'Nature', words: ['water', 'fire', 'mountain', 'hill', 'peak', 'river', 'stream', 'brook', 'lake', 'pond', 'pool', 'sea', 'ocean', 'wave', 'tide', 'waterfall', 'spring', 'sun', 'moon', 'star', 'sky', 'earth', 'land', 'soil', 'stone', 'rock', 'sand', 'mud', 'dust', 'island', 'islet', 'valley', 'cliff', 'cave', 'desert', 'field', 'shore', 'coast', 'beach', 'bay', 'gorge', 'ridge', 'slope', 'nature', 'natural', 'light', 'shadow', 'smoke', 'flame', 'ice', 'gold', 'silver', 'iron', 'copper', 'metal', 'jade', 'coal', 'oil', 'mineral'] },
  { id: 'weather', label: 'Weather', words: ['weather', 'rain', 'snow', 'wind', 'cloud', 'fog', 'mist', 'frost', 'dew', 'thunder', 'lightning', 'storm', 'hail', 'rainbow', 'sunny', 'cloudy', 'hurricane', 'typhoon', 'gale', 'cold', 'hot', 'warm', 'cool', 'freeze', 'frozen', 'dry', 'wet', 'damp', 'humid', 'drought', 'flood', 'climate', 'temperature', 'season', 'spring', 'summer', 'autumn', 'winter'] },
  { id: 'colours', label: 'Colours', words: ['color', 'colour', 'colored', 'coloured', 'red', 'yellow', 'blue', 'green', 'black', 'white', 'purple', 'grey', 'gray', 'brown', 'pink', 'golden', 'orange', 'dark', 'bright', 'pale', 'crimson', 'scarlet', 'azure', 'cyan', 'umber', 'dye', 'paint', 'rouge'] },
  { id: 'time', label: 'Time', words: ['time', 'day', 'daytime', 'week', 'month', 'year', 'hour', 'minute', 'second', 'moment', 'morning', 'noon', 'afternoon', 'evening', 'night', 'midnight', 'dawn', 'dusk', 'today', 'tomorrow', 'yesterday', 'spring', 'summer', 'autumn', 'winter', 'season', 'date', 'calendar', 'clock', 'era', 'epoch', 'age', 'period', 'century', 'generation', 'dynasty', 'ancient', 'past', 'future', 'present', 'now', 'soon', 'late', 'early', 'already', 'before', 'after', 'always', 'forever', 'often', 'sudden', 'suddenly', 'birthday', 'festival', 'holiday'] },
  { id: 'places', label: 'Places', words: ['place', 'country', 'nation', 'state', 'province', 'city', 'town', 'village', 'county', 'district', 'capital', 'home', 'house', 'room', 'school', 'street', 'road', 'lane', 'alley', 'store', 'shop', 'market', 'hospital', 'station', 'airport', 'port', 'harbor', 'harbour', 'temple', 'palace', 'hall', 'building', 'tower', 'bridge', 'park', 'garden', 'farm', 'factory', 'office', 'restaurant', 'hotel', 'inn', 'prison', 'jail', 'tomb', 'north', 'south', 'east', 'west', 'inside', 'outside', 'front', 'above', 'below', 'border', 'region', 'area', 'world', 'abbr', 'europe', 'asia', 'africa', 'america', 'china', 'beijing', 'shanghai'], phrases: ['used in names of places', 'abbr.'] },
  { id: 'home', label: 'Home & objects', words: ['house', 'room', 'door', 'gate', 'window', 'wall', 'roof', 'floor', 'stairs', 'ladder', 'table', 'desk', 'chair', 'stool', 'bed', 'pillow', 'mattress', 'blanket', 'curtain', 'lamp', 'candle', 'mirror', 'cup', 'glass', 'bottle', 'jar', 'bowl', 'plate', 'dish', 'spoon', 'knife', 'pot', 'pan', 'kettle', 'box', 'basket', 'bag', 'bucket', 'key', 'lock', 'bolt', 'nail', 'hammer', 'axe', 'saw', 'rope', 'string', 'thread', 'needle', 'scissors', 'brush', 'comb', 'towel', 'soap', 'umbrella', 'fan', 'tool', 'machine', 'stove', 'oven', 'cabinet', 'drawer', 'shelf', 'frame', 'clock', 'watch', 'phone', 'telephone', 'paper', 'pen', 'ink', 'inkstone', 'book', 'tile', 'brick', 'fence', 'cushion', 'furniture', 'coffin'] },
  { id: 'clothing', label: 'Clothing', words: ['clothes', 'clothing', 'dress', 'garment', 'wear', 'shirt', 'coat', 'jacket', 'robe', 'gown', 'skirt', 'trousers', 'pants', 'sock', 'shoe', 'boot', 'hat', 'cap', 'helmet', 'scarf', 'glove', 'belt', 'sleeve', 'collar', 'button', 'pocket', 'silk', 'satin', 'cotton', 'wool', 'cloth', 'fabric', 'gauze', 'yarn', 'embroider', 'sew', 'knit', 'weave', 'jewellery', 'jewelry', 'bangle', 'bracelet', 'necklace', 'ring', 'hairpin', 'make-up', 'makeup', 'rouge', 'naked', 'nude'] },
  { id: 'school', label: 'School & language', words: ['study', 'learn', 'learning', 'practice', 'practise', 'teach', 'teacher', 'student', 'school', 'class', 'lesson', 'exam', 'examine', 'test', 'read', 'write', 'writing', 'speak', 'say', 'talk', 'speech', 'language', 'word', 'character', 'sentence', 'book', 'letter', 'poem', 'poetry', 'story', 'article', 'chapter', 'page', 'draft', 'edit', 'translate', 'explain', 'answer', 'knowledge', 'know', 'understand', 'think', 'remember', 'forget', 'idea', 'meaning', 'pen', 'paper', 'ink', 'draw', 'paint', 'painting', 'calligraphy', 'music', 'song', 'sing', 'recite', 'rhyme', 'riddle', 'culture', 'art', 'science', 'history', 'philosophy', 'wisdom', 'wise', 'clever', 'stupid', 'research', 'record', 'note', 'script', 'seal'], unless: ['measure word'] },
  { id: 'work', label: 'Work & money', words: ['work', 'job', 'profession', 'occupation', 'career', 'business', 'company', 'factory', 'industry', 'trade', 'money', 'coin', 'currency', 'cash', 'price', 'cost', 'pay', 'salary', 'wage', 'earn', 'profit', 'loss', 'buy', 'sell', 'rich', 'wealth', 'wealthy', 'poverty', 'loan', 'debt', 'owe', 'tax', 'bribe', 'rent', 'hire', 'employ', 'manage', 'manager', 'boss', 'official', 'office', 'market', 'shop', 'store', 'goods', 'product', 'produce', 'economy', 'finance', 'fund', 'capital', 'invest', 'expensive', 'cheap', 'account', 'contract', 'donate', 'yuan', 'dollar', 'pound', 'credit', 'wholesale', 'seller', 'merchant', 'farmer', 'farm', 'craftsman', 'labor', 'labour'] },
  { id: 'travel', label: 'Travel & transport', words: ['travel', 'trip', 'journey', 'tour', 'visit', 'arrive', 'road', 'street', 'path', 'route', 'car', 'vehicle', 'bus', 'train', 'railway', 'rail', 'subway', 'boat', 'ship', 'sail', 'oar', 'anchor', 'plane', 'aircraft', 'airport', 'drive', 'ride', 'bicycle', 'bike', 'wheel', 'carriage', 'sedan', 'cart', 'station', 'port', 'harbor', 'harbour', 'bridge', 'tunnel', 'map', 'passport', 'ticket', 'luggage', 'hotel', 'inn', 'guest', 'transport', 'traffic', 'walk', 'climb'] },
  { id: 'sports', label: 'Sports & play', words: ['play', 'game', 'sport', 'ball', 'match', 'race', 'compete', 'competition', 'contest', 'win', 'team', 'swim', 'run', 'jump', 'dance', 'kick', 'climb', 'chess', 'cards', 'toy', 'kite', 'fishing', 'hunt', 'skate', 'ski', 'exercise', 'gymnastics', 'martial', 'boxing', 'wrestle', 'ping', 'pong', 'drum', 'music', 'sing', 'song', 'party', 'fun', 'joke', 'performance', 'perform', 'film', 'movie', 'drama', 'opera'] },
  { id: 'war', label: 'History & war', words: ['war', 'battle', 'fight', 'army', 'soldier', 'troops', 'military', 'weapon', 'sword', 'spear', 'bow', 'arrow', 'crossbow', 'gun', 'cannon', 'shield', 'armour', 'armor', 'helmet', 'attack', 'defend', 'defense', 'defence', 'enemy', 'invade', 'conquer', 'victory', 'defeat', 'surrender', 'capture', 'prisoner', 'kill', 'slaughter', 'emperor', 'king', 'queen', 'prince', 'princess', 'monarch', 'minister', 'dynasty', 'empire', 'ancient', 'history', 'historical', 'throne', 'court', 'palace', 'general', 'guard', 'bandit', 'rebel', 'revolt', 'beacon'] },
  { id: 'surnames', label: 'Surnames', words: ['surname'], phrases: ['family name'] },
  { id: 'particles', label: 'Grammar words', words: ['particle', 'suffix', 'prefix', 'pronoun', 'conjunction', 'preposition', 'interjection', 'onomatopoeia', 'onomat', 'exclamation', 'transliteration', 'phonetic'], phrases: ['used in', 'not used alone', 'indicate', 'marker', 'modal'] },
];

export type DictionaryFilterId = string;

const escape = (text: string) => text.replace(/[.*+?^${}()|[\]\\-]/g, '\\$&');

export const DICTIONARY_FILTERS = [
  { id: 'all', label: 'All', test: () => true },
  ...DEFINITIONS.map(({ id, label, words, phrases = [], characters = '', unless = [] }) => {
    const wordPattern = words.length ? new RegExp(`\\b(${words.map(escape).join('|')})(s|es)?\\b`, 'i') : null;
    const has = (definition: string, list: string[]) => list.some((phrase) => definition.toLowerCase().includes(phrase));
    return {
      id,
      label,
      // `unless` lets a topic skip definitions that are really about something else.
      test: (entry: CharacterEntry) => characters.includes(entry.character)
        || (!has(entry.definition, unless) && (Boolean(wordPattern?.test(entry.definition)) || has(entry.definition, phrases))),
    };
  }),
] as const;

export function matchesFilter(entry: CharacterEntry, filter: string) {
  return (DICTIONARY_FILTERS.find((candidate) => candidate.id === filter) ?? DICTIONARY_FILTERS[0]).test(entry);
}
