// Chinese-language shows and films to learn from. Trailer IDs and "where to watch" links were checked
// in September 2026; streaming catalogues change and differ by country, so each title also links to JustWatch.

export type FunKind = 'anime' | 'drama' | 'movie' | 'kids';
export type FunLevel = 'Beginner' | 'Intermediate' | 'Advanced';
export type WatchLink = { name: string; url: string; note?: string };

export type Recommendation = {
  id: string;
  title: string;
  chinese: string;
  pinyin: string;
  year: string;
  kind: FunKind;
  level: FunLevel;
  /** What it is about, in a sentence or two. */
  synopsis: string;
  /** Why it helps a learner. */
  why: string;
  /** YouTube video shown as the trailer. */
  trailer: string;
  trailerLabel?: string;
  free: WatchLink[];
  paid: WatchLink[];
};

export const FUN_KINDS: { id: FunKind | 'all'; label: string }[] = [
  { id: 'all', label: 'All' },
  { id: 'anime', label: 'Anime' },
  { id: 'drama', label: 'TV dramas' },
  { id: 'movie', label: 'Movies' },
  { id: 'kids', label: 'Kids' },
];

export const justWatchUrl = (title: string) => `https://www.justwatch.com/us/search?q=${encodeURIComponent(title)}`;

export const RECOMMENDATIONS: Recommendation[] = [
  {
    id: 'peppa-pig',
    title: 'Peppa Pig (Mandarin)',
    chinese: '小猪佩奇',
    pinyin: 'Xiǎo Zhū Pèiqí',
    year: 'Ongoing',
    kind: 'kids',
    level: 'Beginner',
    synopsis: 'Peppa, her little brother George and their family and friends go about everyday life: school, the playground, shopping and jumping in muddy puddles.',
    why: 'Five-minute episodes with slow, clear Mandarin and the same everyday words again and again. The easiest place to start listening.',
    trailer: 'IEQQs7fB1Ms',
    trailerLabel: 'Sample episodes',
    free: [{ name: 'YouTube: 小猪佩奇中文官方 (official channel)', url: 'https://www.youtube.com/@PeppaPigChineseOfficial' }],
    paid: [],
  },
  {
    id: 'a-love-so-beautiful',
    title: 'A Love So Beautiful',
    chinese: '致我们单纯的小美好',
    pinyin: 'Zhì Wǒmen Dānchún de Xiǎo Měihǎo',
    year: '2017',
    kind: 'drama',
    level: 'Beginner',
    synopsis: 'Cheerful Chen Xiaoxi has loved her aloof neighbour Jiang Chen since childhood. A gentle high-school romance that follows them from school into adult life.',
    why: 'Everyday school and family conversations, short scenes and simple modern Mandarin.',
    trailer: 'ReRLQ9GN2iQ',
    trailerLabel: 'Episode 1',
    free: [
      { name: 'Rakuten Viki', url: 'https://www.viki.com/tv/35692c-a-love-so-beautiful', note: 'free with ads' },
      { name: 'YouTube: Viki official playlist', url: 'https://www.youtube.com/playlist?list=PLlH-Fr3fGKJBA1I6NrmsmV4wqIqMULluX' },
    ],
    paid: [{ name: 'Netflix', url: 'https://www.netflix.com/title/80239640' }],
  },
  {
    id: 'hidden-love',
    title: 'Hidden Love',
    chinese: '偷偷藏不住',
    pinyin: 'Tōutōu Cáng Bù Zhù',
    year: '2023',
    kind: 'drama',
    level: 'Intermediate',
    synopsis: 'Sang Zhi has had a secret crush on her brother’s friend Duan Jiaxu since she was a teenager. Years later at university in the same city, the crush turns into something more.',
    why: 'Natural, present-day speech between friends and family, with lots of texting, campus and city vocabulary.',
    trailer: 'tiwcMjH1dRw',
    free: [{ name: 'YouTube: Youku official channel', url: 'https://www.youtube.com/playlist?list=PLIPiKkS-FpK9FBPbX-0X-MDicBEQvjfas', note: 'some episodes' }],
    paid: [
      { name: 'Youku', url: 'https://www.youku.tv/v/v_show/id_XNTk3NTM3NTU4OA==.html' },
      { name: 'Netflix', url: 'https://www.netflix.com/search?q=Hidden%20Love' },
    ],
  },
  {
    id: 'the-untamed',
    title: 'The Untamed',
    chinese: '陈情令',
    pinyin: 'Chén Qíng Lìng',
    year: '2019',
    kind: 'drama',
    level: 'Advanced',
    synopsis: 'Two young cultivators from rival clans, the carefree Wei Wuxian and the upright Lan Wangji, solve mysteries together and are pulled into a war that ends in tragedy.',
    why: 'A fantasy epic with formal, old-fashioned speech. Great for listening once you know the basics; lean on the subtitles.',
    trailer: '2ldvydu34Is',
    free: [
      { name: 'Rakuten Viki', url: 'https://www.viki.com/tv/36657c-the-untamed', note: 'free with ads' },
      { name: 'YouTube: Viki official playlist', url: 'https://www.youtube.com/playlist?list=PLlH-Fr3fGKJBJ4WalTAqjFyvIbmSi_8AI' },
    ],
    paid: [
      { name: 'Netflix', url: 'https://www.netflix.com/title/81200228' },
      { name: 'WeTV', url: 'https://wetv.vip/en/play/gnwjazjgmg997xg-The%20Untamed/d0031smeq8n-EP01:%20The%20Untamed' },
    ],
  },
  {
    id: 'nirvana-in-fire',
    title: 'Nirvana in Fire',
    chinese: '琅琊榜',
    pinyin: 'Láng Yá Bǎng',
    year: '2015',
    kind: 'drama',
    level: 'Advanced',
    synopsis: 'Twelve years after his family is wiped out by a false accusation, a gifted strategist returns to the capital under a new name to clear their names and change who rules.',
    why: 'Widely called one of the best Chinese dramas ever made. Its court language is hard, so it suits advanced learners watching with subtitles.',
    trailer: 'Jdmva52nS9Y',
    free: [
      { name: 'YouTube: China Zone channel (Eng sub)', url: 'https://www.youtube.com/playlist?list=PLtt_YYUGi1gXRt2XVJZrHDBkZECcfmuAJ' },
      { name: 'Plex', url: 'https://watch.plex.tv/show/nirvana-in-fire', note: 'free with ads' },
    ],
    paid: [
      { name: 'Prime Video', url: 'https://www.amazon.com/Nirvana-Fire-%E7%90%85%E7%90%8A%E6%A6%9C-Season-1/dp/B0786Y7JF6' },
      { name: 'Apple TV', url: 'https://tv.apple.com/us/show/nirvana-in-fire/umc.cmc.4bwvcoo8ef8euv8ki6dg0nyki' },
      { name: 'WeTV', url: 'https://wetv.vip/en/play/r4bwi9ou088jxur-Nirvana_in_Fire' },
    ],
  },
  {
    id: 'scissor-seven',
    title: 'Scissor Seven',
    chinese: '刺客伍六七',
    pinyin: 'Cìkè Wǔ Liù Qī',
    year: '2018',
    kind: 'anime',
    level: 'Intermediate',
    synopsis: 'Seven, a clumsy hairdresser on a small island who has lost his memory, takes jobs as a hired assassin to make money, with a talking chicken as his partner.',
    why: 'Short, very funny episodes with fast, casual speech. Watch in Chinese with English subtitles.',
    trailer: '5X8VwQqjTtQ',
    free: [],
    paid: [{ name: 'Netflix', url: 'https://www.netflix.com/title/81156880' }],
  },
  {
    id: 'link-click',
    title: 'Link Click',
    chinese: '时光代理人',
    pinyin: 'Shíguāng Dàilǐrén',
    year: '2021',
    kind: 'anime',
    level: 'Intermediate',
    synopsis: 'Two friends run a photo studio with a secret: they can jump into a photo and live through the moment it was taken, to help clients with regrets. Every job risks changing the past.',
    why: 'Modern everyday Mandarin in a gripping time-travel mystery that makes you want the next episode.',
    trailer: 'Fd6i9zOFFoA',
    free: [],
    paid: [{ name: 'Crunchyroll', url: 'https://www.crunchyroll.com/series/GP5HJ8E81/link-click' }],
  },
  {
    id: 'heaven-officials-blessing',
    title: 'Heaven Official’s Blessing',
    chinese: '天官赐福',
    pinyin: 'Tiān Guān Cì Fú',
    year: '2020',
    kind: 'anime',
    level: 'Advanced',
    synopsis: 'Xie Lian, a prince who became a god and fell from heaven twice, ascends for a third time and investigates ghostly cases with the mysterious Hua Cheng.',
    why: 'Beautiful animation with classical, poetic language. A good stretch for advanced listening.',
    trailer: 'aRhaKwvM360',
    free: [{ name: 'Bilibili', url: 'https://www.bilibili.tv/en/media/35336', note: 'free with ads, some regions' }],
    paid: [{ name: 'Netflix', url: 'https://www.netflix.com/title/81364887' }],
  },
  {
    id: 'ne-zha',
    title: 'Ne Zha',
    chinese: '哪吒之魔童降世',
    pinyin: 'Nézhā zhī Mótóng Jiàngshì',
    year: '2019',
    kind: 'movie',
    level: 'Intermediate',
    synopsis: 'Born from a demon pearl instead of a heavenly one, the boy Ne Zha is feared by everyone and fated to die. He decides to fight his destiny in this animated take on a classic myth.',
    why: 'An animated film with clear voices and lots of humour, plus the Chinese myths every learner meets sooner or later.',
    trailer: 'F37qqQTeIP4',
    free: [{ name: 'Tubi', url: 'https://tubitv.com/movies/703991/ne-zha', note: 'free with ads' }],
    paid: [
      { name: 'Netflix', url: 'https://www.netflix.com/title/81191389' },
      { name: 'Prime Video', url: 'https://www.amazon.com/Ne-Zha-Jiaozi/dp/B0G33CBJP1' },
    ],
  },
  {
    id: 'hi-mom',
    title: 'Hi, Mom',
    chinese: '你好，李焕英',
    pinyin: 'Nǐ Hǎo, Lǐ Huànyīng',
    year: '2021',
    kind: 'movie',
    level: 'Intermediate',
    synopsis: 'After her mother is badly hurt in an accident, Jia Xiaoling is sent back to 1981, where she befriends her young mother and tries to give her a happier life.',
    why: 'A warm comedy about family, with everyday conversation and lots of northern Chinese humour.',
    trailer: 'GjrtxkuFBtk',
    free: [{ name: 'Plex', url: 'https://watch.plex.tv/movie/hi-mom-2021', note: 'free with ads' }],
    paid: [
      { name: 'Prime Video', url: 'https://www.primevideo.com/detail/Hi-Mom/0KZW6KM9KUE7YWTJJR80DY6TSS' },
      { name: 'Google Play', url: 'https://play.google.com/store/movies/details/Hi_Mom?id=5BF401FB22B5CE0CMV' },
    ],
  },
  {
    id: 'the-wandering-earth',
    title: 'The Wandering Earth',
    chinese: '流浪地球',
    pinyin: 'Liúlàng Dìqiú',
    year: '2019',
    kind: 'movie',
    level: 'Intermediate',
    synopsis: 'The Sun is dying, so humanity fits the Earth with giant engines and steers it out of the solar system. When the planet drifts towards Jupiter, a few people must save it.',
    why: 'A big-budget sci-fi blockbuster based on a story by Liu Cixin, with plenty of short, clear dialogue in the action scenes.',
    trailer: '0TDII5IkI3Y',
    free: [],
    paid: [{ name: 'Netflix', url: 'https://www.netflix.com/title/81067760' }],
  },
  {
    id: 'crouching-tiger',
    title: 'Crouching Tiger, Hidden Dragon',
    chinese: '卧虎藏龙',
    pinyin: 'Wò Hǔ Cáng Lóng',
    year: '2000',
    kind: 'movie',
    level: 'Advanced',
    synopsis: 'A legendary sword is stolen, and a veteran warrior and his old friend chase the thief into a world of secret loves and martial-arts duels in Qing dynasty China.',
    why: 'The Oscar-winning classic of wuxia film. The dialogue is formal and the actors’ accents vary, so watch it with subtitles.',
    trailer: 'GRQ9CGnEmWQ',
    free: [{ name: 'The Roku Channel', url: 'https://therokuchannel.roku.com/details/681a475fd202dba8826885a265ab8088/crouching-tiger-hidden-dragon', note: 'free with ads' }],
    paid: [
      { name: 'Netflix', url: 'https://www.netflix.com/title/60002907' },
      { name: 'Apple TV', url: 'https://tv.apple.com/us/movie/crouching-tiger-hidden-dragon/umc.cmc.1qyopok7zvm57lvbxa2oz4ibq' },
    ],
  },
  {
    id: 'pleasant-goat',
    title: 'Pleasant Goat and Big Big Wolf',
    chinese: '喜羊羊与灰太狼',
    pinyin: 'Xǐ Yángyáng yǔ Huī Tàiláng',
    year: '2005',
    kind: 'kids',
    level: 'Beginner',
    synopsis: 'Big Big Wolf keeps inventing new schemes to catch the goats of Green Green Grassland, and clever Pleasant Goat and his friends outsmart him every time.',
    why: 'China’s best-loved cartoon. Short episodes with simple, repetitive dialogue that every Chinese child knows.',
    trailer: 'XiFDDDuw4a4',
    trailerLabel: 'Episode 1',
    free: [{ name: 'YouTube: 喜羊羊与灰太狼 official Chinese channel', url: 'https://www.youtube.com/channel/UCbELDDHGqMbjsA_4Kyd7vMw' }],
    paid: [],
  },
  {
    id: 'boonie-bears',
    title: 'Boonie Bears',
    chinese: '熊出没',
    pinyin: 'Xióng Chūmò',
    year: '2012',
    kind: 'kids',
    level: 'Beginner',
    synopsis: 'Two bear brothers, Briar and Bramble, protect their forest home from Logger Vick, a lumberjack who keeps trying to cut the trees down.',
    why: 'Slapstick comedy that is easy to follow even when you miss words, with lots of everyday spoken Chinese.',
    trailer: 'nZplu3bQMuY',
    trailerLabel: 'Full movie',
    free: [{ name: 'YouTube: 熊出没 Boonie Bears official channel', url: 'https://www.youtube.com/channel/UCexhmwhQ2zmBDt2Q6qM3hdg' }],
    paid: [],
  },
  {
    id: 'cocomelon-chinese',
    title: 'CoComelon (Mandarin)',
    chinese: '可可瓜儿歌',
    pinyin: 'Kěkěguā Érgē',
    year: '2021',
    kind: 'kids',
    level: 'Beginner',
    synopsis: 'JJ and his family sing nursery rhymes and songs about everyday life: bath time, colours, numbers, animals and manners.',
    why: 'Songs repeat the same simple words many times, which makes them great for pronunciation and tones.',
    trailer: 'EJ6JWs2MvUQ',
    trailerLabel: 'Sample song',
    free: [{ name: 'YouTube: CoComelon 中文版 official channel', url: 'https://www.youtube.com/channel/UC9oCMwabf-4jTTC3GN4hjew' }],
    paid: [{ name: 'Netflix', url: 'https://www.netflix.com/search?q=CoComelon', note: 'switch the audio to Mandarin' }],
  },
  {
    id: 'love-between-fairy-and-devil',
    title: 'Love Between Fairy and Devil',
    chinese: '苍兰诀',
    pinyin: 'Cāng Lán Jué',
    year: '2022',
    kind: 'drama',
    level: 'Intermediate',
    synopsis: 'A lowly orchid fairy and a feared demon lord accidentally become bound together, so whatever happens to one is felt by the other, and an unlikely love grows between them.',
    why: 'A fun, fast-moving fantasy romance with lots of comedy and a mix of modern and old-style speech.',
    trailer: 'l4AMenAv9pg',
    free: [
      { name: 'iQIYI', url: 'https://www.iq.com/album/love-between-fairy-and-devil-2022-ld8e5pprpl?lang=en_us', note: 'free with ads' },
      { name: 'Rakuten Viki', url: 'https://www.viki.com/tv/38664c-love-between-fairy-and-devil', note: 'free with ads' },
    ],
    paid: [{ name: 'Netflix', url: 'https://www.netflix.com/title/81622849' }],
  },
  {
    id: 'story-of-yanxi-palace',
    title: 'Story of Yanxi Palace',
    chinese: '延禧攻略',
    pinyin: 'Yánxǐ Gōnglüè',
    year: '2018',
    kind: 'drama',
    level: 'Advanced',
    synopsis: 'Wei Yingluo enters the Forbidden City as a maid to find out who killed her sister, and uses her wits to survive palace schemes and rise through the Qing court.',
    why: 'One of the most-watched Chinese dramas ever. The palace language is formal, so it is best with subtitles.',
    trailer: 'Z4xLnxser7s',
    free: [
      { name: 'iQIYI', url: 'https://www.iq.com/album/story-of-yanxi-palace-2018-15yrzo9s2o9?lang=en_us', note: 'free with ads' },
      { name: 'YouTube: 欢娱影视 (the producer’s channel)', url: 'https://www.youtube.com/playlist?list=PLhnjbkseqMETBEoxI9sgYqp3snAlnXeHI' },
    ],
    paid: [],
  },
  {
    id: 'meteor-garden',
    title: 'Meteor Garden',
    chinese: '流星花园',
    pinyin: 'Liúxīng Huāyuán',
    year: '2018',
    kind: 'drama',
    level: 'Beginner',
    synopsis: 'Down-to-earth student Dong Shancai stands up to F4, the four rich and arrogant boys who run her university, and ends up falling for their leader.',
    why: 'A classic campus romance with clear, everyday modern Mandarin and plenty of simple, emotional dialogue.',
    trailer: '87Q8hTratnM',
    free: [],
    paid: [{ name: 'Netflix', url: 'https://www.netflix.com/title/81005504' }],
  },
  {
    id: 'mo-dao-zu-shi',
    title: 'Mo Dao Zu Shi',
    chinese: '魔道祖师',
    pinyin: 'Mó Dào Zǔ Shī',
    year: '2018',
    kind: 'anime',
    level: 'Advanced',
    synopsis: 'Wei Wuxian, a feared cultivator who died years ago, is brought back to life in a stranger’s body and teams up with his old friend Lan Wangji to solve a string of dark mysteries.',
    why: 'The animated version of the story behind The Untamed, told in beautiful, literary Chinese.',
    trailer: 'YsA1hKfRqtQ',
    free: [{ name: 'YouTube: Tencent Video animation playlist', url: 'https://www.youtube.com/playlist?list=PLFQ_OmrLPETHs-Sm7T7Czpi6tqvv98s0K' }],
    paid: [{ name: 'Crunchyroll', url: 'https://www.crunchyroll.com/search?q=Master%20of%20Diabolism', note: 'as “The Master of Diabolism”' }],
  },
  {
    id: 'soul-land',
    title: 'Soul Land',
    chinese: '斗罗大陆',
    pinyin: 'Dòu Luó Dàlù',
    year: '2018',
    kind: 'anime',
    level: 'Intermediate',
    synopsis: 'Tang San, a martial artist reborn into a world where everyone awakens a spirit power, trains at an academy for spirit masters and sets out to become the strongest of all.',
    why: 'One of the most popular donghua. Long-running, with the same training and battle words coming up again and again.',
    trailer: 'M7lE49GNbf4',
    trailerLabel: 'Episode 1',
    free: [{ name: 'YouTube: Tencent Video animation', url: 'https://www.youtube.com/watch?v=M7lE49GNbf4', note: 'early episodes' }],
    paid: [{ name: 'YouTube channel membership', url: 'https://www.youtube.com/playlist?list=PLxOs22nkVmnJV5YGIKqb1I7v-9g7KdMGk', note: 'every episode' }],
  },
  {
    id: 'kings-avatar',
    title: 'The King’s Avatar',
    chinese: '全职高手',
    pinyin: 'Quánzhí Gāoshǒu',
    year: '2017',
    kind: 'anime',
    level: 'Intermediate',
    synopsis: 'Ye Xiu, a top pro gamer forced out of his team, starts again from scratch at an internet café and builds a new team to fight his way back to the top.',
    why: 'Modern everyday and gaming vocabulary, with lots of banter between friends.',
    trailer: 'ZKPyyFM9sCw',
    free: [{ name: 'YouTube: Viki official playlist', url: 'https://www.youtube.com/playlist?list=PLlH-Fr3fGKJBVYuFmtI6Fx89W6ZeHwdSK' }],
    paid: [
      { name: 'Netflix', url: 'https://www.netflix.com/title/81175361' },
      { name: 'WeTV', url: 'https://wetv.vip/play/pnumjfjcvuau4sr-The-King%27s-Avatar-(Dongman)' },
    ],
  },
  {
    id: 'big-fish-begonia',
    title: 'Big Fish & Begonia',
    chinese: '大鱼海棠',
    pinyin: 'Dà Yú Hǎitáng',
    year: '2016',
    kind: 'movie',
    level: 'Intermediate',
    synopsis: 'Chun, a girl from a hidden world beneath the sea, visits the human world as a red dolphin. When a boy dies saving her, she risks everything to bring him back.',
    why: 'A gorgeous animated film full of Chinese folklore, with calm, clear dialogue.',
    trailer: 'ErQLQMpRPXk',
    free: [],
    paid: [{ name: 'Netflix', url: 'https://www.netflix.com/title/80233883', note: 'some countries' }],
  },
  {
    id: 'hero',
    title: 'Hero',
    chinese: '英雄',
    pinyin: 'Yīngxióng',
    year: '2002',
    kind: 'movie',
    level: 'Advanced',
    synopsis: 'A nameless swordsman tells the king of Qin how he defeated three legendary assassins, but each retelling of the story reveals a different truth.',
    why: 'Zhang Yimou’s famous wuxia epic. Spoken slowly and formally, with stunning visuals that carry the story.',
    trailer: 'MgsddFEe9Oc',
    free: [],
    paid: [{ name: 'Rent or buy (Amazon, Google Play, YouTube)', url: 'https://www.justwatch.com/us/movie/hero-2002' }],
  },
  {
    id: 'yolo',
    title: 'YOLO',
    chinese: '热辣滚烫',
    pinyin: 'Rè Là Gǔn Tàng',
    year: '2024',
    kind: 'movie',
    level: 'Intermediate',
    synopsis: 'Du Leying has spent years shut away at home. After meeting a boxing coach, she decides to change her life and trains for a real boxing match.',
    why: 'From the director of Hi, Mom: funny, moving and full of natural, present-day conversation.',
    trailer: 'Dbr4tS9uyks',
    free: [],
    paid: [
      { name: 'Prime Video', url: 'https://www.primevideo.com/detail/0JGUS0VCPEB4VFF1HLHUEZDANK' },
      { name: 'Apple TV', url: 'https://tv.apple.com/us/movie/yolo-%E7%83%AD%E8%BE%A3%E6%BB%9A%E7%83%AB/umc.cmc.6lpixp27d4ipaeu1uaxpzlz7l' },
      { name: 'Google Play', url: 'https://play.google.com/store/movies/details/Yolo_China?id=rDjDoAzGKnA.P' },
    ],
  },
];

/** A stable number for a string, so the same month always gives the same picks. */
function hash(text: string) {
  let value = 2166136261;
  for (let index = 0; index < text.length; index++) value = Math.imul(value ^ text.charCodeAt(index), 16777619);
  return value >>> 0;
}

/** This month's featured titles: one from every section, then the next best, in an order that changes each month. */
export function monthlyPicks(year: number, month: number, count = 5) {
  const shuffled = [...RECOMMENDATIONS].sort((first, second) => hash(`${first.id}:${year}-${month}`) - hash(`${second.id}:${year}-${month}`));
  const picks: Recommendation[] = [];
  for (const item of shuffled) if (!picks.some((pick) => pick.kind === item.kind)) picks.push(item);
  for (const item of shuffled) if (picks.length < count && !picks.includes(item)) picks.push(item);
  return picks.slice(0, count).sort((first, second) => shuffled.indexOf(first) - shuffled.indexOf(second));
}
